#include <Arduino.h>
#include "AXS15231B.h"
#include "esp_heap_caps.h"
#include <NimBLEDevice.h>
#include <Preferences.h>
#include <Wire.h>
#include "track_names.h"
#include "racebox.h"
#include "laptimer.h"

extern uint32_t transfer_num;
extern size_t lcd_PushColors_len;
static uint16_t *nativeFrame=nullptr,*screen=nullptr;
static String raceboxes[8],raceboxAddr[8]; static uint8_t raceboxAddrType[8]={0};
static int raceboxCount=0,selectedRacebox=0,listPage=0,savedRaceboxIndex=-1;
static bool touchDown=false,touchLocked=false,rbConnected=false,askLastDevice=false;
static Preferences prefs; static String savedRbAddr="",connectedAddr="";
static NimBLEClient *rbClient=nullptr; static NimBLERemoteCharacteristic *rbTx=nullptr,*rbRx=nullptr;
#define TOUCH_ADDR 0x3B
#define TOUCH_SCL 10
#define TOUCH_SDA 15
#define TOUCH_INT 11
#define TOUCH_RST 16
static inline uint16_t C(uint16_t v){return (uint16_t)((v<<8)|(v>>8));}
static void rect(int x,int y,int w,int h,uint16_t c){if(x<0){w+=x;x=0;}if(y<0){h+=y;y=0;}if(x+w>640)w=640-x;if(y+h>180)h=180-y;if(w<=0||h<=0)return;for(int yy=y;yy<y+h;yy++)for(int xx=x;xx<x+w;xx++)screen[(size_t)yy*640+xx]=c;}
static void present(){for(int y=0;y<180;y++)for(int x=0;x<640;x++)nativeFrame[(size_t)x*180+(179-y)]=screen[(size_t)y*640+x];lcd_PushColors(0,0,180,640,nativeFrame);}
static const uint8_t DIG[12][5]={{0x3E,0x51,0x49,0x45,0x3E},{0,0x42,0x7F,0x40,0},{0x42,0x61,0x51,0x49,0x46},{0x21,0x41,0x45,0x4B,0x31},{0x18,0x14,0x12,0x7F,0x10},{0x27,0x45,0x45,0x45,0x39},{0x3C,0x4A,0x49,0x49,0x30},{0x01,0x71,0x09,0x05,0x03},{0x36,0x49,0x49,0x49,0x36},{0x06,0x49,0x49,0x29,0x1E},{0,0x36,0x36,0,0},{0,0x60,0x60,0,0}};
static void glyph(int x,int y,int id,int s,uint16_t col){for(int cx=0;cx<5;cx++)for(int cy=0;cy<7;cy++)if(DIG[id][cx]&(1<<cy))rect(x+cx*s,y+cy*s,s,s,col);}
static void num(int x,int y,const char*t,int s,uint16_t col){while(*t){int id=-1;if(*t>='0'&&*t<='9')id=*t-'0';else if(*t==':')id=10;else if(*t=='.')id=11;if(id>=0)glyph(x,y,id,s,col);else if(*t=='+'||*t=='-'){rect(x,y+3*s,5*s,s,col);if(*t=='+')rect(x+2*s,y+s,s,5*s,col);}x+=6*s;t++;}}
static void numTallBold(int x,int y,const char*t,int sx,int sy,uint16_t col){while(*t){int id=-1;if(*t>='0'&&*t<='9')id=*t-'0';else if(*t==':')id=10;else if(*t=='.')id=11;if(id>=0)for(int cx=0;cx<5;cx++)for(int cy=0;cy<7;cy++)if(DIG[id][cx]&(1<<cy))rect(x+cx*sx,y+cy*sy,sx+1,sy,col);x+=6*sx;t++;}}
static const uint8_t ALPHA[26][5]={{0x7E,0x11,0x11,0x11,0x7E},{0x7F,0x49,0x49,0x49,0x36},{0x3E,0x41,0x41,0x41,0x22},{0x7F,0x41,0x41,0x22,0x1C},{0x7F,0x49,0x49,0x49,0x41},{0x7F,0x09,0x09,0x09,0x01},{0x3E,0x41,0x49,0x49,0x7A},{0x7F,0x08,0x08,0x08,0x7F},{0,0x41,0x7F,0x41,0},{0x20,0x40,0x41,0x3F,0x01},{0x7F,0x08,0x14,0x22,0x41},{0x7F,0x40,0x40,0x40,0x40},{0x7F,0x02,0x0C,0x02,0x7F},{0x7F,0x04,0x08,0x10,0x7F},{0x3E,0x41,0x41,0x41,0x3E},{0x7F,0x09,0x09,0x09,0x06},{0x3E,0x41,0x51,0x21,0x5E},{0x7F,0x09,0x19,0x29,0x46},{0x46,0x49,0x49,0x49,0x31},{0x01,0x01,0x7F,0x01,0x01},{0x3F,0x40,0x40,0x40,0x3F},{0x1F,0x20,0x40,0x20,0x1F},{0x7F,0x20,0x18,0x20,0x7F},{0x63,0x14,0x08,0x14,0x63},{0x03,0x04,0x78,0x04,0x03},{0x61,0x51,0x49,0x45,0x43}};
static void text5(int x,int y,const char*t,int s,uint16_t col){while(*t){char ch=*t++;if(ch==' '){x+=4*s;continue;}int id=-1;if(ch>='A'&&ch<='Z')id=ch-'A';else if(ch>='a'&&ch<='z')id=ch-'a';if(id>=0)for(int cx=0;cx<5;cx++)for(int cy=0;cy<7;cy++)if(ALPHA[id][cx]&(1<<cy))rect(x+cx*s,y+cy*s,s,s,col);x+=6*s;}}
static void fmtLap(uint32_t ms,char*out,size_t n){uint32_t m=ms/60000u;ms%=60000u;snprintf(out,n,"%02lu:%02lu.%03lu",(unsigned long)m,(unsigned long)(ms/1000u),(unsigned long)(ms%1000u));}
static void fmtDelta(int32_t ms,char*out,size_t n){char sign=ms<=0?'-':'+';uint32_t a=(uint32_t)(ms<0?-ms:ms);snprintf(out,n,"%c%lu.%03lu",sign,(unsigned long)(a/1000u),(unsigned long)(a%1000u));}
static void saveRaceBox(const String&a){prefs.begin("proot",false);prefs.putString("rbAddr",a);prefs.end();savedRbAddr=a;}
static void scanRaceBoxes(){NimBLEDevice::init("");NimBLEDevice::setPower(ESP_PWR_LVL_P9);NimBLEScan*scan=NimBLEDevice::getScan();scan->setActiveScan(true);scan->setInterval(100);scan->setWindow(99);NimBLEScanResults found=scan->getResults(10000,false);raceboxCount=0;int used[8];for(int&i:used)i=-1;for(int slot=0;slot<8;slot++){int best=-1,bestRssi=-999;for(int i=0;i<found.getCount();i++){bool already=false;for(int k=0;k<slot;k++)if(used[k]==i)already=true;if(already)continue;const NimBLEAdvertisedDevice*d=found.getDevice(i);if(d&&d->getRSSI()>bestRssi){best=i;bestRssi=d->getRSSI();}}if(best<0)break;used[slot]=best;const NimBLEAdvertisedDevice*d=found.getDevice(best);raceboxes[raceboxCount]=d->haveName()?String(d->getName().c_str()):String("BLE");raceboxAddr[raceboxCount]=String(d->getAddress().toString().c_str());raceboxAddrType[raceboxCount]=d->getAddress().getType();raceboxCount++;}}
enum ConnectState:uint8_t{CONN_IDLE,CONN_WORKING,CONN_OK,CONN_FAIL};static volatile ConnectState connState=CONN_IDLE;static volatile int connIndex=-1;static ConnectState drawnConnState=CONN_IDLE;
static bool probeRaceBoxIndex(int idx){if(idx<0||idx>=raceboxCount)return false;String addr=raceboxAddr[idx];NimBLEAddress target(std::string(addr.c_str()),raceboxAddrType[idx]);NimBLEClient*stale=NimBLEDevice::getClientByPeerAddress(target);if(stale)NimBLEDevice::deleteClient(stale);NimBLEClient*client=NimBLEDevice::createClient();if(!client||!client->connect(target)){if(client)NimBLEDevice::deleteClient(client);return false;}NimBLERemoteService*svc=client->getService("6E400001-B5A3-F393-E0A9-E50E24DCCA9E");if(!svc){client->disconnect();NimBLEDevice::deleteClient(client);return false;}rbRx=svc->getCharacteristic("6E400002-B5A3-F393-E0A9-E50E24DCCA9E");rbTx=svc->getCharacteristic("6E400003-B5A3-F393-E0A9-E50E24DCCA9E");if(!rbRx||!rbTx||!rbTx->canNotify()||!rbTx->subscribe(true,RaceBox::notify)){client->disconnect();NimBLEDevice::deleteClient(client);rbRx=rbTx=nullptr;return false;}rbClient=client;rbConnected=true;connectedAddr=addr;RaceBox::setConnection(client,rbRx,true);saveRaceBox(addr);return true;}
static bool probeRaceBoxAddress(const String&a){for(int i=0;i<raceboxCount;i++)if(raceboxAddr[i].equalsIgnoreCase(a))return probeRaceBoxIndex(i);return false;}
static void raceBoxConnectTask(void*){int idx=connIndex;bool ok=idx>=0&&idx<raceboxCount&&probeRaceBoxAddress(raceboxAddr[idx]);connState=ok?CONN_OK:CONN_FAIL;vTaskDelete(NULL);}
static void startRaceBoxConnect(int idx){if(connState==CONN_WORKING)return;connIndex=idx;connState=CONN_WORKING;xTaskCreatePinnedToCore(raceBoxConnectTask,"rb-connect",8192,nullptr,1,nullptr,0);}
static void persistCustomLine(){LapTimerLine l=LapTimer::line();prefs.begin("proot",false);prefs.putBool("sfOk",l.valid);if(l.valid){prefs.putDouble("sfLat",l.lat);prefs.putDouble("sfLon",l.lon);prefs.putDouble("sfDx",l.dirX);prefs.putDouble("sfDy",l.dirY);}prefs.end();}
static void clearCustomLinePrefs(){prefs.begin("proot",false);prefs.putBool("sfOk",false);prefs.remove("sfLat");prefs.remove("sfLon");prefs.remove("sfDx");prefs.remove("sfDy");prefs.end();}
static void drawRaceBoxLive(){uint16_t black=C(0),white=C(0xFFFF),green=C(0x07E0),lightgray=C(0xC618),red=C(0xF800),yellow=C(0xFFE0),darkgray=C(0x2104);const RaceBoxTelemetry&t=RaceBox::telemetry();const LapTimerState&s=LapTimer::state();for(size_t i=0;i<180u*640u;i++)screen[i]=black;if(s.customLine)text5(6,6,"Custom",2,white);else if(s.factoryTrack&&s.factoryTrackIndex>=0){const char*p=(const char*)pgm_read_ptr(&PROOT_TRACK_NAMES[s.factoryTrackIndex]);char name[40];strncpy_P(name,p,sizeof(name)-1);name[sizeof(name)-1]=0;text5(6,6,name,2,white);}char now[16],mainTime[16];uint32_t elapsed=(s.running&&t.towMs>=s.lapStartTow)?t.towMs-s.lapStartTow:0;fmtLap(elapsed,now,sizeof(now));bool flash=s.flashStarted&&millis()-s.flashStarted<5000u;if(s.stopped&&s.bestLapMs)fmtLap(s.bestLapMs,mainTime,sizeof(mainTime));else if(flash)fmtLap(s.lastLapMs,mainTime,sizeof(mainTime));else snprintf(mainTime,sizeof(mainTime),"%s",now);uint16_t mainCol=(s.stopped&&s.bestLapMs)?green:((flash&&s.lastLapMs&&s.lastLapMs==s.bestLapMs)?green:white);if(flash){numTallBold(128,44,mainTime,8,13,mainCol);present();return;}numTallBold(6,48,mainTime,5,9,mainCol);char lapNo[3];snprintf(lapNo,sizeof(lapNo),"%02u",(unsigned)(s.lapCount%100));text5(243,156,"LAP",2,yellow);numTallBold(288,122,lapNo,7,7,yellow);rect(287,0,80,80,darkgray);text5(295,28,"STOP",3,white);if(touchLocked)text5(303,88,"RAIN",2,white);if(!s.stopped){char lt[16],bt[16],dt[16],ang[12];fmtLap(s.lastLapMs,lt,sizeof(lt));fmtLap(s.bestLapMs,bt,sizeof(bt));if(s.deltaValid)fmtDelta(s.deltaMs,dt,sizeof(dt));else snprintf(dt,sizeof(dt),"+0.000");num(382,0,dt,7,s.deltaValid?(s.deltaMs<=0?green:red):white);text5(382,74,"LEAN",2,yellow);snprintf(ang,sizeof(ang),"%+.1f",t.leanDeg);num(442,60,ang,6,lightgray);text5(382,119,"L",3,white);num(422,113,lt,4,white);text5(382,153,"B",3,green);num(422,147,bt,4,green);}else{int first=(int)s.historyPage*3;for(int row=0;row<3;row++){int idx=first+row,y=8+row*55;if(idx>=s.historyCount)break;char no[4],tm[16];uint32_t h=LapTimer::history(idx);snprintf(no,sizeof(no),"%02d",idx+1);fmtLap(h,tm,sizeof(tm));num(382,y,no,3,yellow);num(424,y,tm,3,(h&&h==s.bestLapMs)?green:white);}if(s.historyCount>3){rect(590,0,50,60,darkgray);rect(590,120,50,60,darkgray);text5(602,8,"UP",1,white);text5(602,158,"DN",1,white);}}rect(12,115,70,60,darkgray);uint16_t smCol=s.running?green:red;text5(23,156,"S",2,smCol);for(int i=0;i<10;i++)rect(35+i,165-i,2,2,smCol);text5(47,156,"M",2,smCol);rect(88,115,70,60,darkgray);text5(103,156,"SAT",2,t.sats?green:red);rect(164,115,70,60,darkgray);text5(179,156,"REC",2,RaceBox::recordingEnabled()?green:red);present();}
static bool readTouch(int&lx,int&ly){uint8_t cmd[8]={0xb5,0xab,0xa5,0x5a,0,0,0,8},b[14]={0};Wire.beginTransmission(TOUCH_ADDR);Wire.write(cmd,8);if(Wire.endTransmission()!=0)return false;if(Wire.requestFrom(TOUCH_ADDR,14)!=(size_t)14)return false;Wire.readBytes(b,14);if(!b[1]||b[0])return false;int nx=((b[2]&15)<<8)|b[3],ny=((b[4]&15)<<8)|b[5];lx=constrain(639-nx,0,639);ly=constrain(179-ny,0,179);return true;}
static void drawLastDevicePrompt(){uint16_t black=C(0),white=C(0xFFFF),green=C(0x07E0),red=C(0xF800),gray=C(0x4208);for(size_t i=0;i<180u*640u;i++)screen[i]=black;text5(92,22,"CONNECT TO LAST DEVICE",3,white);if(savedRaceboxIndex>=0){String id="";for(int k=0;k<raceboxes[savedRaceboxIndex].length();k++)if(isDigit(raceboxes[savedRaceboxIndex][k]))id+=raceboxes[savedRaceboxIndex][k];if(id.length()>10)id=id.substring(id.length()-10);if(id.length())num(248,62,id.c_str(),3,gray);}rect(70,108,220,54,green);text5(145,122,"YES",4,black);rect(350,108,220,54,red);text5(435,122,"NO",4,white);present();}
static void drawRaceBoxList(){uint16_t black=C(0),white=C(0xFFFF),green=C(0x07E0),gray=C(0x4208),red=C(0xF800),dark=C(0x2104);for(size_t i=0;i<180u*640u;i++)screen[i]=black;int pages=max(1,(raceboxCount+2)/3);if(listPage>=pages)listPage=pages-1;int first=listPage*3;for(int row=0;row<3;row++){int i=first+row,y=18+row*50;if(i>=raceboxCount)break;uint16_t col=gray;if(i==selectedRacebox){if(connState==CONN_WORKING)col=C(0xFFE0);else if(connState==CONN_OK&&rbConnected)col=green;else if(connState==CONN_FAIL)col=red;}rect(12,y,300,38,col);num(22,y+7,String(i+1).c_str(),3,black);}rect(390,12,190,42,dark);text5(447,22,"UP",3,white);rect(390,126,190,42,dark);text5(447,136,"DN",3,white);present();}
void setup(){Serial.begin(115200);delay(200);pinMode(PIN_BUTTON_1,INPUT_PULLUP);pinMode(TFT_BL,OUTPUT);digitalWrite(TFT_BL,HIGH);pinMode(TOUCH_RST,OUTPUT);digitalWrite(TOUCH_RST,HIGH);delay(2);digitalWrite(TOUCH_RST,LOW);delay(10);digitalWrite(TOUCH_RST,HIGH);Wire.begin(TOUCH_SDA,TOUCH_SCL);pinMode(TOUCH_INT,INPUT);axs15231_init();size_t n=180u*640u;nativeFrame=(uint16_t*)heap_caps_malloc(n*2,MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);screen=(uint16_t*)heap_caps_malloc(n*2,MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!nativeFrame||!screen)return;for(size_t i=0;i<n;i++)screen[i]=C(0);rect(0,0,640,4,C(0x07E0));text5(24,48,"AEP",10,C(0xFFFF));text5(230,48,"Racing",4,C(0xFFFF));text5(230,88,"Development",3,C(0x4208));present();prefs.begin("proot",true);savedRbAddr=prefs.getString("rbAddr","");bool sfOk=prefs.getBool("sfOk",false);double sfLat=prefs.getDouble("sfLat",0),sfLon=prefs.getDouble("sfLon",0),sfDx=prefs.getDouble("sfDx",0),sfDy=prefs.getDouble("sfDy",0);prefs.end();RaceBox::reset();LapTimer::reset();if(sfOk)LapTimer::restoreCustomStartFinish(sfLat,sfLon,sfDx,sfDy);scanRaceBoxes();if(savedRbAddr.length())for(int i=0;i<raceboxCount;i++)if(raceboxAddr[i].equalsIgnoreCase(savedRbAddr)){selectedRacebox=i;savedRaceboxIndex=i;break;}while(transfer_num>1){lcd_PushColors(0,0,0,0,NULL);delay(1);}if(savedRaceboxIndex>=0){askLastDevice=true;drawLastDevicePrompt();}else drawRaceBoxList();}
void loop(){static uint32_t resetPress=0;static bool resetDone=false;bool resetDown=digitalRead(PIN_BUTTON_1)==LOW;if(resetDown&&!resetPress&&!resetDone)resetPress=millis();if(resetDown&&resetPress&&!resetDone&&millis()-resetPress>=3000u){touchLocked=!touchLocked;resetDone=true;resetPress=0;if(connState==CONN_OK&&rbConnected)drawRaceBoxLive();}if(!resetDown){resetPress=0;resetDone=false;}if(transfer_num<=1&&lcd_PushColors_len>0)lcd_PushColors(0,0,0,0,NULL);RaceBox::process();LapTimer::update(RaceBox::telemetry());if(!askLastDevice&&connState!=drawnConnState){drawnConnState=connState;if(connState==CONN_OK&&connIndex>=0){selectedRacebox=connIndex;saveRaceBox(raceboxAddr[selectedRacebox]);}if(connState==CONN_FAIL)drawRaceBoxList();}static bool timingShown=false;static uint32_t connOkSince=0,lastDraw=0;if(connState==CONN_OK&&rbConnected){if(!connOkSince)connOkSince=millis();if(!timingShown&&millis()-connOkSince>=750){drawRaceBoxLive();timingShown=true;}if(timingShown&&RaceBox::telemetry().liveValid&&millis()-lastDraw>=100){lastDraw=millis();drawRaceBoxLive();}}else{connOkSince=0;timingShown=false;}int x=0,y=0;bool down=readTouch(x,y);if(askLastDevice&&down&&!touchDown){if(y>=108&&y<162&&x>=70&&x<290){askLastDevice=false;selectedRacebox=savedRaceboxIndex;rbConnected=false;startRaceBoxConnect(savedRaceboxIndex);}else if(y>=108&&y<162&&x>=350&&x<570){askLastDevice=false;drawRaceBoxList();}}else if(connState==CONN_OK){static uint32_t stopPress=0;static bool stopLong=false;bool onStop=x>=287&&x<367&&y<80;if(!touchLocked&&down&&!touchDown&&onStop)stopPress=millis();if(!touchLocked&&down&&stopPress&&!stopLong&&millis()-stopPress>=1500u){RaceBox::requestRecording(false);LapTimer::reset();clearCustomLinePrefs();stopLong=true;stopPress=0;drawRaceBoxLive();}if(!touchLocked&&!down&&touchDown){if(stopPress&&!stopLong&&millis()-stopPress<1500u){RaceBox::requestRecording(false);LapTimer::stop();drawRaceBoxLive();}stopPress=0;stopLong=false;}if(!touchLocked&&down&&!touchDown&&!onStop){if(x>=12&&x<82&&y>=115&&y<175){LapTimer::setCustomStartFinish(RaceBox::telemetry());persistCustomLine();RaceBox::requestRecording(true);drawRaceBoxLive();}else if(x>=164&&x<234&&y>=115&&y<175){RaceBox::requestRecording(!RaceBox::recordingEnabled());drawRaceBoxLive();}else if(x>=590&&y<60){LapTimer::historyPageUp();drawRaceBoxLive();}else if(x>=590&&y>=120){LapTimer::historyPageDown();drawRaceBoxLive();}}}else if(connState!=CONN_OK&&down&&!touchDown&&x>=390&&x<580&&y>=12&&y<54){int pages=max(1,(raceboxCount+2)/3);listPage=(listPage+pages-1)%pages;drawRaceBoxList();}else if(connState!=CONN_OK&&down&&!touchDown&&x>=390&&x<580&&y>=126&&y<168){int pages=max(1,(raceboxCount+2)/3);listPage=(listPage+1)%pages;drawRaceBoxList();}else if(connState!=CONN_OK&&down&&!touchDown&&x>=12&&x<312&&y>=18&&y<156){int row=(y-18)/50,idx=listPage*3+row;if(idx>=0&&idx<raceboxCount){selectedRacebox=idx;rbConnected=false;startRaceBoxConnect(idx);}}touchDown=down;delay(20);}
