#pragma once
#include <Arduino.h>
static const char* const PROOT_TRACK_NAMES[] PROGMEM={
"Polsat Plus",
"Ahvenanmaa",
"Grandvalira",
"A1-Speedworld",
"Bad Fischau",
"Brandlhof",
"Fuglau",
"Greinbach",
"Melk",
"RC Aigen",
"Red Bull Ring (A1)",
"Salzburgring",
"Speedarena Rechnitz",
"Styria Karting",
"Tulln Langenlebarn",
"DOSAAF",
"Amay cobra",
"Bedrijvenpark Kortrijk-Noord",
"Gedinne",
"Genk",
"Karting de Fagnes",
"Mettet",
"Model Race Genk",
"Roeselare RC",
"Spa francorchamps karting",
"Spa-Francorchamps",
"Zolder",
"Zaluzani",
"A1 Motor Park",
"Blagoevgrad",
"Boyana",
"Buhovo",
"Burgas 2022",
"Circuit Sofia",
"Circuit Stara Zagora",
"Dolna Mitropolia",
"Dolni Chiflik",
"Haskovo",
"Haskovo 2020",
"Kaloyanovo",
"Karting Academy Tvarditsa",
"Konza",
"Krasna polqna",
"Kyustendil",
"Lauta",
"Multi RC Shumen",
"Osogovo Hill climb",
"Pleven",
"RC Novi Iskar",
"RC Trud",
"Ruse",
"Sapareva Banya",
"Shumen",
"Sofia",
"Sopot",
"Todor Slavov",
"Varna",
"Veliko Tarnovo",
"Vratsa",
"Vratsa - RC",
"Grobnik",
"Kartodrom Bura",
"Novi Marof",
"Rijeka",
"UMAG",
"Achna Speedway",
"Daytona",
"Brno",
"Cheb",
"KartPlanet",
"Most",
"Pisek",
"Sosnova",
"Trinec Steelring",
"Vysoke Myto",
"Yamaha Moravia",
"Als Go Kart Club",
"Auning",
"Barmosen",
"Djursland",
"Grindsted",
"Hillerod RC",
"Holbaek",
"Jyllands Ringen",
"Kobenhavns",
"Korsor",
"Lovelbanen",
"Marielyst",
"Midtjysk",
"Motorsport Center Fyn",
"Mou",
"Naestved Model Racing Club",
"Padborg Park",
"Randers",
"Rodby Karting Ring",
"Roskilde",
"Sjaellandsringen FDM",
"Skaerbaek",
"Sonderso",
"Svebolle Go Kart",
"Thy Karting Center",
"Vandel",
"Vojens",
"Aravete",
"Auto24Ring",
"Kaina",
"Laitse",
"Poltsamaa",
"Rapla",
"Tabasalu",
"Ahvenisto",
"Alaharma mika salo",
"Alastaro",
"Botniaring",
"Daytona Circuit Akaa",
"Espoo",
"Forssa",
"Hamina",
"Hanko",
"Helsinki",
"Honkajoki",
"Hyvinkaa",
"Imatra",
"Jamsa",
"Joensuu",
"Kaanaa",
"Kangasala",
"Kauhajoki",
"Kemora",
"Kitee",
"Kokemaki",
"Kotka",
"Kouvola",
"Kuopio",
"Kymi Ring",
"Lahti",
"Lapinlahti",
"Lappeenranta",
"Lapua",
"Linatti",
"Loviisa",
"Monako",
"MotoPark",
"Nurmeksen",
"OuluZone",
"OuluZone (2)",
"Paimio",
"Pello",
"Pieksamaki",
"Pori",
"Riihimaki",
"Rovaniemi",
"Ruuhimaki",
"Saarijarvi",
"Savonlinna",
"Suonenjoki",
"Suseka",
"Toijala",
"Turku",
"Tykkimaen",
"Ulvila",
"Vaasa",
"Vantaa",
"Varkaus",
"Vihti",
"Ylivieska huhmarkallio",
"74 mk circuit",
"A.S.K Ancenis",
"Abbeville",
"Abbeville kart",
"ACS karting",
"ACS Peugeot Mulhouse",
"Actua Lyon",
"Actua Lyon east",
"Actua Lyon west",
"Alain prost",
"Albi",
"Angely",
"Angerville",
"Anim",
"Anneau Du Rhin",
"ASK Laval",
"ASK Loheac kart",
"Atlantic",
"Attigny",
"Aunis",
"Autoreille",
"Auxois",
"Auxois go-kart",
"Ayrton Senna small",
"Beaucaire",
"Belval",
"Berdery",
"Bergerac",
"Bicetre",
"Biguglia",
"Biky concept",
"Boule d or",
"Bourbonnais",
"Bouscaillous",
"Bresse",
"Bresse GP",
"Bretagne",
"Brignoles Karting Loisir",
"BRK Beltoise",
"Bruno garcia",
"Buffo les etards",
"Butte Verte",
"Cabourg",
"Cadours",
"Caen",
"Cap",
"Carole",
"Carole GP",
"Caudecoste",
"Caussiniojouls",
"Chambley",
"Champforgeuil",
"Charade",
"Chenevieres",
"Circuit du Laquais",
"Clastres",
"Clotkart",
"Correze",
"Cosne",
"Croix",
"Crolles chrono",
"Daniel Pescheur",
"Deauville",
"Deauville small",
"Dellaroli",
"Dijon",
"Dijon-Prenois",
"Douvrin",
"Dreux",
"Driving Centre, Castellet",
"du Var",
"Ducas",
"Dunois",
"Dynamic",
"Ecuyers",
"EIA",
"Eleceka",
"Electric Fast Cars Fenouillet",
"Elite",
"Escale",
"Escource",
"Espace loisirs",
"Espace plus",
"Espoey",
"Essay",
"Etauliers",
"Euro dieppe",
"Eurokart France",
"Europe",
"Extrem",
"Fay de Bretagne",
"Folembray",
"Fontenay Le Comte",
"Formula kart",
"Foulain",
"Fouteau",
"Fun",
"Gaillou",
"Garden",
"Generation",
"GEOPARC",
"GKL 53",
"GP circuit",
"Gravelines",
"Gravona",
"Grimaud",
"Hague",
"Hardt",
"Haute Saintonge",
"Haute saintonge",
"Hirson",
"Inter",
"Issoire",
"JPB pondinois",
"Jurasud",
"Kart 66",
"Kart center",
"Kart Center de Narp-Biscarosse",
"Kart ocean",
"Kart System",
"Karting 2 Muret",
"Karting 55",
"Karting 79",
"Karting Circuit Paul Ricard",
"Karting de l'Etang",
"Karting du Bugey",
"Karting Plus",
"Kartix parc",
"Kartland",
"Kerlabo",
"KLN",
"KLN small",
"L enclos small",
"L Indre",
"La calmette",
"La Chatre",
"La Ferte Gaucher",
"La manche",
"LADOUX MICHELIN DRY",
"Ladoux Michelin WET",
"Lambert",
"Lavaud",
"Lavilledieu",
"Le creusot",
"Le Mans",
"Ledenon",
"Levier",
"Lezennes",
"Loc",
"Loche mousseloniere",
"Loheac",
"Loisir 86",
"Loisir de lescotais",
"Loisirs",
"Lonny",
"Lucien Lebret",
"Lurcy Levis",
"Lyon OnlyKart",
"MACN",
"Made in",
"Magescq",
"Magny Cours",
"Malmongere",
"Manacha",
"Marais",
"Marseillan plage",
"Mas du Clos",
"Mathieu Vidal",
"Maurice chomat",
"Mecamax",
"Megakart",
"Meisenthal",
"Merignac",
"Metropole",
"Michetterie",
"Mirecourt",
"Mirecourt Auto",
"Mistral kart one",
"MODELESPACE",
"Moncoutant RC",
"Mont blanc",
"Montmartin promeca sport",
"Montreux",
"Mornay",
"Mortainais",
"Nancy",
"Nogaro",
"NRC VIAIS",
"Number one",
"Oceane",
"Oratoire",
"Ouest",
"Ouistreham",
"Pau Amos gokart",
"Pau Arnos",
"Paul Ricard",
"Perigord",
"Pers",
"PH sports",
"Philippe alliot",
"Planche",
"Ploemel",
"Plumeliau kart center",
"PMRC",
"Pole Mecanique Car",
"Pole Mecanique Karting",
"Prestige",
"Prokart Figari",
"Promo sports",
"Quad de montalivet",
"Quad sensations",
"RACG Grenoble",
"RCY",
"Renardieres",
"Renaudin de witry",
"Rennes parc expo",
"RKC",
"RLS karting",
"Roussillon",
"Rove",
"Royan",
"Rumilly",
"Saint amand",
"Saint Malo",
"Saint ponchon",
"Saintes",
"Salbris",
"Sambuc",
"Sarl evolution",
"Sarron",
"Saulcy",
"Sautron",
"Sens espaces",
"Sens espaces small",
"SKLC 55",
"Small Circuit Magny Cours",
"Solokart",
"Speed fun",
"St lye DB",
"Starter park",
"Sud",
"Sud Toulois",
"Sun Karting",
"Sundgau",
"Sunkart",
"Super karting loisir",
"Technikart",
"Thiais",
"Top Gun Evasion",
"Torreilles",
"Touraine",
"Tours karting",
"Trappes",
"Trets",
"Trois lacs",
"Vaison Piste",
"Val d argenton",
"Val de Vienne",
"Val de Vienne (B)",
"Valence",
"Vallee",
"Varennes sur Allier",
"Vers de vase",
"Villars",
"West aventure",
"Win kart",
"Wittenheim",
"Rustavi International Motorpark",
"ADAC Steisslingen",
"Alfsee",
"Altes lager",
"AMC MUEHLAU",
"Ampfing",
"AMSC Augsburg",
"ATP Papenburg",
"Bassum",
"Belleben",
"Bilster Berg",
"Bilster Berg (Westschleife)",
"Brookmerland",
"Bueren",
"Dahlemer binz",
"Dargelin",
"Driving Center Baden Airpark",
"Driving Center Gross Dolln",
"Driving Center Gross Dolln (C)",
"Emsbueren",
"Emslandring",
"Erftlandring",
"Erlebniswelt Voglsam",
"Erzgebirgsring Lichtenberg",
"Fassberg",
"Freibahn",
"Gerolzhofen",
"Gorlitz-Ring",
"Hansakarting",
"Harsewinkel",
"Harz ring",
"Heidbergring",
"Hockenheimring",
"Kaiserkuhle",
"Kart 2000",
"Kartbahn Amberg",
"Kartsport-Zentrum Rottal",
"Kiki",
"Lausitz go-kart",
"Lausitzring",
"Liedolsheim",
"Loeschen",
"Luneburg",
"Michael Schumacher Kart",
"Motodrom Hagen",
"Motordrom",
"Motorsportarena Mulsen",
"MRC Leipzig",
"MSC Bopfingen",
"Nordseering",
"Norisring",
"Nurburgring",
"Nurburgring (Grand Prix Strecke)",
"Nurburgring (Nordschleife (T13))",
"Nussloch",
"Oberberg",
"Oberlandring",
"Odenwaldring",
"Ortenauring",
"Oschersleben",
"Oschersleben (C)",
"Oschersleben karting",
"Porsche Experience Center Track",
"Porsche Leipzig",
"Racepark Meppen",
"Ramsloh",
"Ramsloh (2)",
"RC Ettlingen",
"RS kartcenter",
"Saarlandring",
"Sachsenring",
"Saxonia go-kart",
"Schleiz",
"Schleswigring",
"Schlusselfeld",
"Schoenerlinde",
"Speedy",
"Spreewaldring",
"STC Spreewald Ring",
"Stefan Bellof",
"Straubing",
"Templiner ring",
"Vogelsbergring",
"Wackersdorf",
"Waldparkring",
"Westerwaldring",
"Ae center",
"AHLADOKABOS HILLCLIMB",
"Chalkis",
"Chania Pista Park",
"Circuit27",
"Drive park",
"Eprepe RC",
"Kardamena",
"Kartland (2)",
"KartLand Malia",
"Kartodromo Afidnes",
"Lagada",
"Macedonia RC",
"Marmari",
"Mega drive",
"Megara",
"Memphis",
"Messara",
"San Nikolas Kalamata",
"Serres Automotive",
"Serres kart",
"SFi KARTING",
"Sparta Racing Circuit MOTUL",
"Spavo Race21",
"Speed Force",
"Speed Park",
"Thunderkarts - Corinth GoKart",
"Balaton",
"Balaton Park",
"Bognar",
"Dakar Ring",
"Euroring",
"GoKart Farm",
"Gokart Stadion",
"Gyula",
"Hungaroring",
"Kakucs Ring",
"Kiskunlachaza",
"M Ring",
"Nyirad",
"Paloc Ring",
"Pannonia Ring",
"Pannonia Ring Karting",
"Rabocsi ring",
"SER-Ring Gokartpalya",
"Speedway Gokart Palya",
"Vac",
"Visonta",
"Kartworld adventure",
"Mondello Park",
"Whiteriver Karting International",
"Jurby manx",
"7 Laghi Kart Castelletto",
"Acqua parco",
"Adria",
"Adria Raceway",
"Adriatico",
"Ala",
"Alberone",
"Alessandro Beatrice",
"Alfa Romeo",
"Alle Cave",
"ALPI MARITTIME",
"Amato",
"Ananda Sporting Club",
"Aprilia",
"Arcobaleno",
"Artena",
"Asd model drivers Arezzo",
"ASD Tribe Model",
"Associazione sportiva",
"Atina",
"Autodromo di Modena",
"AutomodelTerni RC",
"Azzurra",
"Azzurra Borgoticino",
"Balocco High Speed",
"Balocco Langhe",
"Balocco Shift Durability",
"Bi karting",
"Binetto",
"Campioni",
"Carasco",
"Casaluce",
"Castelletto di Branduzzo",
"Caudina",
"Cavalletto laquila",
"Cerrina",
"Chioggia",
"Christel Village",
"Circuito di Monsano",
"Civitavecchia",
"Club Des Miles",
"Cogis Kart",
"Concordia",
"Cremona",
"Cremona karting",
"D oro",
"del Corallo",
"Del mare",
"Del sele",
"Del sole",
"Dino Ferrari",
"Domitiana",
"Don paolo",
"Euro kart",
"Extrema",
"Fanelli",
"Feggiani",
"Fiorano",
"Fiorano RC",
"Fluida",
"Franciacorta",
"Franciacorta Karting",
"Franco meloni",
"Funnyland",
"Galliano Park",
"Gela",
"Giacomo Premoli",
"Gialla del salinello",
"Gianni de Luca",
"Ginosa Marina",
"Gravina",
"Gubbio RC",
"Happy Valley",
"IL PISTONE",
"Imola",
"Imola2",
"International Circuit Hills",
"Is Arenadas",
"Isam",
"Iscaro",
"Jeeper cross",
"Jeepers Kart - Cattolica",
"Jolly park",
"Jonica",
"Kart Roma",
"Karting 90",
"Karting Stella",
"Kartodomo Dino Falco",
"Kartodromo di Villarosa",
"Kinisia",
"Kobra",
"La Conca",
"La mola",
"La Pista Centro Guida",
"La Rampa",
"LaClinica OffRoad",
"Lascari",
"Le Colline",
"Leopard Circuit Viterbo",
"Lignano",
"Lombardore",
"Magione",
"Maruggio go kart",
"Messina",
"Mini Pista Leno",
"Miniautodromo Giancarlo Chiriaco",
"Miniautodromo Ombrone",
"Miniautodromo Teramo",
"Miniautodromo Vallelunga",
"Minicar Montegiorgio",
"Minimoto San Mauro",
"Minoa",
"Misanino",
"Misano",
"Mondovi",
"Monza",
"Mores",
"Mugello",
"Mugello Grand Prix",
"Mycandy Arena",
"Nardo Handling",
"Naxos World",
"Oasi",
"Oleandri",
"Orobico",
"Ortona",
"Ozzano Motor Valley",
"Palladio",
"Palomba",
"Paradise",
"Paradiso",
"Parco Motori La Chiusa",
"Parona Pista",
"Pfatten",
"Pista Di Montecchio",
"Pista il Geko",
"Pista Melzo",
"Pista Moscufo",
"Pitom Circuit",
"Planet",
"Poggio",
"Pomposa",
"Pomposa - Big",
"Racing Park Viadana",
"Rastellino",
"RC Capriano",
"RC Kronion",
"RC Locorotondo",
"Riccardo Borile",
"Riccione",
"Riccione Circuit",
"Rioveggio",
"Ronco",
"Rozzano",
"Sagittario",
"Salandra",
"San marco",
"San Martino gokart",
"Santa caterina",
"Santa cecilia",
"Santa venera",
"Sarno",
"Siena",
"Sirene",
"Sole luna",
"Sole Luna Vittoria",
"South Garda Karting",
"South milano",
"Sport club",
"Stradivari Cremona",
"Sulmona",
"Talao sunday",
"Tazio Nuvolari",
"Tibikart",
"Tolmezzo",
"Torracing",
"Torretta",
"Torricola MinimotoVR",
"Touch Go Martina Franca",
"Tramatza",
"Triscina",
"Ugento",
"Val Vibrata",
"Valle dei Templi",
"Valle del Liri",
"Vallelunga",
"Varano",
"Ve be",
"Verde",
"Villanovafranca",
"Vincenza Ispica",
"Vittoria",
"Volturno",
"Winner",
"X Bikes Circuit Ferrara",
"Bikernieki",
"Bikernieki Karting",
"Kandava",
"Madona",
"Rullitis",
"SK333",
"Anyksciu Kart",
"Aukstadvario",
"Drif Go Baciunu",
"Nemunas Ring",
"Palanga",
"Plytines",
"Serbentu kartodromas MANDE",
"Smalininkai",
"Mondercange",
"RC Ville de Luxembourg",
"Podgorica",
"Berghem",
"Driebergen",
"Eefde",
"Eindhoven",
"Kartcentrum Lelystad",
"Kartcentrum Lelystad (2)",
"Kartcentrum Zwolle",
"KCNN",
"MACH Heemstede",
"Midland",
"Oldenzaal",
"Pottendijk",
"RC Apeldoorn",
"RC Gouda",
"RC Real 80",
"RC Rucphen",
"RC Velp",
"Strijen",
"TT Circuit Assen",
"TT Junior",
"Utrecht Onroad",
"Venray",
"Zandvoort",
"Zandvoort (Oostelijk)",
"ABC Eggemoen",
"Alesund",
"Arctic Circle",
"Eikas",
"Gjervag Motorbane",
"Grenland Motorsport",
"Haugaland Motorsenter",
"KNA Oppland Elvedalen",
"KNA Raceway",
"KNA Varna",
"Kongsberg Motorsenter Gokart",
"Krakenesmarka",
"Lista",
"Malmedalen Motorsenter",
"NMK Andebu",
"NMK Trogstad",
"Reve",
"Rudskogen",
"Rudskogen GoKart",
"Sigdal",
"Starmoen",
"Valerbanen",
"Valerbanen go kart",
"Vamoen Motorsportsenter AS",
"Autodrom Pomorze",
"Awix Racing Arena",
"Bemowo",
"Bydgoszcz",
"Energetyk bilgoraj",
"Gostyn",
"Kielce",
"Moto Park Krakow",
"Motopark koszalin",
"Poznan",
"Poznan Automotive",
"Radom",
"Rallycross Track Torun",
"Silesia Ring",
"Suwalki",
"Szczecin",
"Tor Bialystok",
"Tor Jastrzab",
"Tor Krzywa",
"Tor Lodz",
"Tor Modlin",
"Tor Slomczyn",
"Wallrav Race Center",
"Abrantes",
"Alcanede Kart",
"Algarve",
"Almansil",
"Almeirim",
"AMF Vila Real",
"Baltar",
"Batalha",
"Braga",
"Campera",
"Castelo Branco",
"Circuito do Sol",
"Dino kart",
"Estoril",
"Evora",
"Fatima",
"Kartodromo Braga",
"Kartodromo do Faial",
"KIRO",
"Leiria",
"Loja Kip",
"Odivelas",
"Oia",
"Portimao",
"Porto cabo do mundo",
"Sto andre",
"Viana",
"Vilela",
"VN poiares",
"AMCKART",
"Bacau",
"Circuitul Skat Kart",
"Masterkart",
"Motor Park",
"Prejmer Raceway",
"Transilvania Motor Ring",
"ADM Myachkovo",
"ASK Virazh",
"Atron International",
"Firsanovka",
"Igora Drive",
"KazanRing Canyon",
"Kursk",
"Lemar",
"Lider",
"Mayak",
"Moscow Raceway",
"NRing",
"Primorskoye Koltso",
"Sibkart",
"Simbirsk",
"Smolensk Ring",
"Sochi",
"STK Pilot",
"Ada Huja",
"MOTODROM KULA",
"National Driving Academy (NAVAK)",
"DLHA Karting",
"Dunajska Streda",
"Slovak Karting Center",
"Slovakia Ring",
"Trebatice",
"AMZS Center Varne",
"AMZS Slovenja Vas",
"Gas Vrtejba",
"Lindau Ring",
"Raceland Krsko",
"AF Karting",
"Alacant",
"Albacete",
"Albaida",
"Alcarras",
"Alcarras GP",
"Almenara",
"Almeria",
"Angel Burgueno",
"Ariza",
"Ascari",
"Ascari gokart",
"Aspar Circuit",
"Autet Valencia RC",
"Bennykarts",
"Cabanillas",
"Caceres",
"Calafat",
"Can picafort",
"Cardedeu",
"CARSOL ELCHE",
"Cartagena",
"Cartaya",
"Castelloli",
"Castroponce",
"Catalunya",
"Catalunya (Club)",
"Chicano",
"Circuito Gasss74 Karting",
"Circuito Yepes Motor",
"Cordoba",
"Correcaminos",
"Del Sol",
"DR7 Daniel Rivas",
"El pla",
"El templo del motor",
"Elche Karting Club",
"Finestrat",
"FK1",
"Formula 5",
"Fortuna Motorsport",
"Francis",
"Garrucha",
"Gijon",
"Godocar",
"Gran Karting Club Junior",
"Gran Karting Club Senior",
"Guadix",
"Henakart",
"Jarama",
"Javea",
"Jerez",
"Juneda",
"Karting Cabanas Raras",
"Karting Campillos Int",
"Karting Coma-Ruga",
"Karting Empuriabrava",
"Karting La Vila",
"Karting San Pablo",
"Kartodromo Valga",
"Kartpetania",
"Kotarr",
"KR24 Sanlucar",
"KVR",
"La Madalena",
"La Manga",
"La roca",
"La Selva",
"La torre",
"La Torrica",
"Lanzarote",
"Lanzarote small",
"Las Americas",
"Las Minas",
"Los santos",
"Lucas Guerrero",
"Luis Climent",
"Luis climent",
"Magaluf",
"Mallorca",
"Mallorca kart",
"Maspalomas",
"Matanza",
"Menarguens 55-84",
"Miranda",
"Monteblanco",
"Mora",
"Mora d ebre",
"Motorland Aragon",
"Motorland aragon",
"Motorland Aragon (West)",
"Mozota",
"Nabella",
"Navarra",
"Navarra gokart",
"Ocana",
"Ocio luis miguel",
"Ociokart",
"Olaberria",
"Oliva Valencia",
"Oriokart",
"Oropesa",
"Osona vic",
"Parcmotor castelloli",
"Parcmotor castelloli small",
"Parque del Motor",
"Pinto",
"Porrino",
"Quercus Vega",
"Regencos",
"Ricardo Tormo",
"Roses",
"Sallent",
"Samper de calandra",
"San javier",
"Santa Eularia",
"Sanxenxo",
"Sevilla",
"Sevilla Circuit",
"Sills",
"Soto duenas",
"Talavera",
"Tapia",
"Tenerife",
"Tepesa",
"Tordesillas",
"Vendrell",
"Villarcayo",
"Vinaros",
"Zuera",
"Anderstorp",
"Anderstorp (North)",
"Arlanda",
"Axamo",
"Borlange",
"Drivecenter Arena",
"Emmaboda Flygbana",
"Enkoping",
"Falkenberg",
"Gellerasen",
"Goteborgs",
"Gotland",
"Gotland Ring",
"Granges hyrkart",
"GTR Motorpark",
"Hagaslatt",
"Halla Ring",
"Hassleholms RC HRCBK",
"Hedemora",
"Helsingborgs",
"Jarfalla",
"Karlskoga",
"Katrineholm",
"Kinnekulle Ring",
"Klippan",
"Knutstorp",
"Kristianstad",
"Lidkoping",
"Linkoping go-kart",
"Ljungbyheds Motorbana",
"Lockarps",
"Lulea Karting",
"Mantorp Park",
"Mittsverigebanan",
"Molanda",
"Monztabanan",
"Ostersund",
"Rattvik",
"Rorberg",
"Rorken",
"SAABs Testrack",
"Skostorpsbanan",
"Skovde",
"Sturup Raceway",
"Sviestad",
"Tierp Arena",
"Tuvangen Ring",
"Uddevalla",
"Ward motor ab",
"Kappelen AG",
"Lignieres",
"Locarno",
"RC Lostallo",
"Sulgen AG",
"Vuitboeuf",
"Wohlen",
"Istanbul Park",
"Izmit korfez",
"Kenan Sofuoglu Circuit",
"KNN54 Kenan Sofuoglu",
"MyTrack, Kula",
"STS karting",
"Tosfed Korfez",
"Tuzla",
"Ulkupark",
"Usak",
"Chaika gokart",
"Chaika Raceway",
"Chaika Raceway (Long)",
"Crimea",
"Dnipro Kart",
"Ltava",
"Mykolaiv",
"Need for speed",
"Adur Model Car Club",
"Aintree",
"Aldershot Raceway",
"Amen Corner",
"Ancaster Leisure",
"Anglesey",
"Anglia",
"Arlington Stadium",
"Bayford Meadows",
"Bedford",
"Bedford (East)",
"Bedford (North)",
"Bedford (South)",
"Birmingham Wheels",
"Bishopscourt",
"Blyton Park Race Track",
"Border",
"Bradford",
"Brands Hatch",
"Brentwood",
"Brighton",
"Buckmore",
"Cadwell Park",
"Camberley",
"Campbell",
"Carew",
"Castle Combe",
"Chequered flag",
"Clay Pigeon Raceway",
"Croft",
"Cromer",
"Curborough",
"Darley Moor",
"Donington Park",
"East Scotland Kart Club",
"Eastbourne Electric Car Club",
"Elk racing",
"Ellough Park",
"Forest Edge",
"Fulbeck",
"G force",
"Glan y Gors Park (GYG)",
"Glasfryn",
"Golspie",
"Goodwood",
"Gosford",
"Grampian Kart",
"Gurston Down",
"Halifax RC",
"Harewood Speed Hillclimb",
"Haynes",
"Hednesford Hills Raceway",
"Herefordshire",
"Hooton Park",
"Hungarian hall",
"Karting North East",
"Karting world",
"Kartworld",
"Kimbolton",
"Kirkistown",
"Knockhill",
"Knockhill (2)",
"Lakeside Karting",
"Larkhall",
"Little Rissington",
"Llandow",
"Llandow GP",
"Lochgelly Oval",
"Lochgelly Raceway",
"Loton Park Hill Climb",
"Lydd International",
"Lydden Hill",
"Mallory Park",
"Mansell Raceway",
"Matchams",
"Milton Keynes",
"Nottingham",
"Nutts Corner",
"Olivers Mount Racing",
"Oulton Park",
"Oxford",
"Parkwood",
"Pembrey",
"Pembrey gokart",
"Pf international",
"Prescott Hill Climb",
"Pro-Am",
"Raceland",
"Red Lodge",
"Rednal",
"Rockingham",
"Rowrah",
"Rye House Kart Raceway",
"Sandown Park",
"Shelsley Walsh",
"Shenington",
"Silverstone",
"Silverstone (GP wing pits)",
"Silverstone Kart",
"Snetterton",
"South Coast Karting",
"Spedeworth",
"Stretton",
"Surbiton",
"Sutton",
"Swaffham",
"Tamworth",
"Tattershall",
"Teesside",
"Three Sisters Race Circuit",
"Thruxton",
"Thruxton go-kart",
"Trax",
"Whilton Mill",
"Whilton Mill small",
"Wildtracks",
"Wildtracks (long)",
"Wiscombe",
"Wombwell",
};
